// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20230211143103_initialWithSeed")]
    partial class initialWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnName("Origin")
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Route");

                    b.HasData(
                        new
                        {
                            Id = new Guid("541a18d4-2ba8-4a6e-addb-6ff8670023bb"),
                            Destination = "BRC",
                            Origin = "GRU",
                            Value = 10m
                        },
                        new
                        {
                            Id = new Guid("2fcb9645-28d5-4cd3-a09c-c9b657676d26"),
                            Destination = "SCL",
                            Origin = "BRC",
                            Value = 5m
                        },
                        new
                        {
                            Id = new Guid("6644f2c0-035e-426a-bc7a-42419337f60e"),
                            Destination = "CDG",
                            Origin = "GRU",
                            Value = 75m
                        },
                        new
                        {
                            Id = new Guid("04c490f6-41eb-4202-8264-35a60d3f1454"),
                            Destination = "SCL",
                            Origin = "GRU",
                            Value = 20m
                        },
                        new
                        {
                            Id = new Guid("e386472f-0de9-419a-b118-13806fe5e0b9"),
                            Destination = "ORL",
                            Origin = "GRU",
                            Value = 56m
                        },
                        new
                        {
                            Id = new Guid("5cf3653c-4497-49b1-a831-0ddb1de869b9"),
                            Destination = "CDG",
                            Origin = "ORL",
                            Value = 5m
                        },
                        new
                        {
                            Id = new Guid("498566a5-7235-43cd-ab88-d301430b2034"),
                            Destination = "ORL",
                            Origin = "SCL",
                            Value = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
